# Generated by Django 3.1 on 2020-08-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_globalconacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconacts',
            name='spam',
            field=models.BooleanField(default=False),
        ),
    ]
